///////////////////////////////////////////////////////////
//  RicercaTipo.cs
//  Implementation of the Class RicercaTipo
//  Generated by Enterprise Architect
//  Created on:      04-ott-2014 15.49.14
//  Original author: Nicolas
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace MUSEICA.Model
{

    public class RicercaTipo : IRicercaProvider
    {
        private ITipologiaSala _iTipologiaSalaToFind;

        public RicercaTipo(ITipologiaSala iTipologiaSalaToFind)
        {
            _iTipologiaSalaToFind = iTipologiaSalaToFind;
        }

        public List<Prenotazione> Ricerca(List<Prenotazione> prenotazioni)
        {
            List<Prenotazione> result = new List<Prenotazione>();
            foreach (Prenotazione p in prenotazioni)
            {
                if (_iTipologiaSalaToFind.NomeTipologia.ToLower().Equals(p.Sala.Tipo.NomeTipologia.ToLower()))
                    result.Add(p);
            }

            return result;
        }

    }
}